### ISSUE TITLE
Memory error with Calibir GXM

### ISSUE THREAD

**Issue by e-team-t** [jcramer/pyGigE-V#6]
Tried the test.py and got the following error:

It is not getting the height right,

('OK', {'username': '...', 'macLow': ..., 'fIPv6': False, 'ipAddr': 3232248480L, 'ipAddrHigh': 0L, 'host': {'ipAddrHigh': 0L, 'ipAddr': 3232248331L, 'fIPv6': False, 'ipAddrLow': 0L, 'ifIndex': 2L}, 'serial': '...', 'manufacturer': 'Teledyne DALSA', 'macHigh': 1L, 'capabilities': 0L, 'version': '000', 'ipAddrLow': 0L, 'model': 'Calibir GXM640'}, 2)

Initial image parameters:
{'code': 0, 'height': 52982716563936L, 'width': 640L, 'pixelFormat': (17301505L, '0x1080001L'), 'y_offset': 0L, 'x_offset': 0L}

Final image parameters:
{'code': 0, 'height': 52982716563936L, 'width': 640L, 'pixelFormat': (17301505L, '0x1080001L'), 'y_offset': 0L, 'x_offset': 0L}

Traceback (most recent call last):
  File "test.py", line 43, in <module>
    ctx.GevInitializeImageTransfer(1)
  File "pygigev.pyx", line 105, in pygigev.PyGigEV.GevInitializeImageTransfer
    self.buffers = np.empty(shape=[numImgBuffers,size], dtype=np.uint8, order="C")
MemoryError
Segmentation fault (core dumped)

**Comment by e-team-t** [comment]
This is related to 
Accessing multiple gige camera #5
